CREATE TABLE `GHU` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `EMAIL` VARCHAR(255) NOT NULL,
  `TOKEN` VARCHAR(32) NOT NULL,
  `GUESS` INT(11),
  `SEGP` TINYINT,
  `SEFP` TINYINT,
  `SERP` TINYINT,
  PRIMARY KEY (`ID`)
);
