REATE TABLE `HGHU` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATE` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
  `WTOKEN` VARCHAR(32) NOT NULL,
  `WGUESS` INT NOT NULL,
  `CSV` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`)
);
