CREATE TABLE `META` (
  `MAIN` INT(11) NOT NULL,
  `STATE` INT(11) NOT NULL,
  `RP` INT(11) NOT NULL,
  `GP` INT(11) NOT NULL,
  `FP` INT(11) NOT NULL,
  `NOP` INT(11) NOT NULL,
  `NOG` INT(11) NOT NULL,
  PRIMARY KEY (`MAIN`)
);
